(function () {
    'use strict';
    const ROOMS_KEY = 'ulivre_blackjack_rooms';
    const WALLET_KEY = 'ulivre_blackjack_wallets';
    const STARTING_COINS = 250;
    const MAX_BET = 250;
    const SUITS = ['♠', '♥', '♦', '♣'];
    const RANKS = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
    let activeRoomId = null;
    let game = null;
    const panel = () => document.getElementById('blackjackPanel');
    const tx = (key, fallback) => { const value = typeof window.t === 'function' ? window.t(key) : key; return value === key ? fallback : value; };
    const userName = () => (localStorage.getItem('userProfileName') || tx('games_room_player_label', 'Jogador')).trim();
    const playerId = () => { let id = sessionStorage.getItem('ulivre_blackjack_player_id'); if (!id) { id = `blackjack-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; sessionStorage.setItem('ulivre_blackjack_player_id', id); } return id; };
    const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
    function readRooms() { try { const rooms = JSON.parse(localStorage.getItem(ROOMS_KEY) || '[]'); return Array.isArray(rooms) ? rooms.filter(room => window.UniversidadeLivreGameScope?.matchesRoom(room) ?? true) : []; } catch (_) { return []; } }
    function writeRooms(rooms) { let all = []; try { all = JSON.parse(localStorage.getItem(ROOMS_KEY) || '[]'); } catch (_) {} const other = Array.isArray(all) ? all.filter(room => !(window.UniversidadeLivreGameScope?.matchesRoom(room) ?? true)) : []; localStorage.setItem(ROOMS_KEY, JSON.stringify([...other, ...rooms].slice(-20))); }
    const getRoom = (id = activeRoomId) => readRooms().find(room => room.id === id) || null;
    function wallet() { if (window.UniversidadeLivreWallet) return window.UniversidadeLivreWallet.get(); let wallets = {}; try { wallets = JSON.parse(localStorage.getItem(WALLET_KEY) || '{}'); } catch (_) {} if (!wallets[userName()]) wallets[userName()] = { coins: STARTING_COINS, wins: 0, hands: 0 }; return wallets[userName()]; }
    function saveWallet(value) { if (window.UniversidadeLivreWallet) { window.UniversidadeLivreWallet.update({ ...value, activeGame: 'blackjack' }); return; } let wallets = {}; try { wallets = JSON.parse(localStorage.getItem(WALLET_KEY) || '{}'); } catch (_) {} wallets[userName()] = { ...value, coins: Math.max(0, Math.floor(value.coins)) }; localStorage.setItem(WALLET_KEY, JSON.stringify(wallets)); }
    function drawCard() { return { rank: RANKS[Math.floor(Math.random() * RANKS.length)], suit: SUITS[Math.floor(Math.random() * SUITS.length)] }; }
    function cardValue(card) { return card.rank === 'A' ? 11 : ['K','Q','J'].includes(card.rank) ? 10 : Number(card.rank); }
    function score(hand) { let total = hand.reduce((sum, card) => sum + cardValue(card), 0); let aces = hand.filter(card => card.rank === 'A').length; while (total > 21 && aces) { total -= 10; aces -= 1; } return total; }
    function createRoom() { const target = panel(); const mode = target.querySelector('#blackjackMode')?.value || 'community'; const room = window.UniversidadeLivreGameScope?.decorateRoom({ id:`BJK-${Math.random().toString(36).slice(2,7).toUpperCase()}`, owner:playerId(), mode, players:[{ id:playerId(), name:userName() }], capacity:2, createdAt:Date.now(), game:null }); if (mode === 'bot') room.players.push({ id:`bot-${room.id}`, name:tx('blackjack_bot','Bot'), isBot:true }); activeRoomId = room.id; sessionStorage.setItem('ulivre_blackjack_active_room', activeRoomId); writeRooms([...readRooms(), room]); startRoom(room); }
    function joinRoom(id) { const room = getRoom(id); if (!room || room.mode === 'bot' || room.players.length >= room.capacity) return; room.players.push({ id:playerId(), name:userName() }); activeRoomId=id; sessionStorage.setItem('ulivre_blackjack_active_room',id); writeRooms(readRooms().map(item => item.id === id ? room : item)); startRoom(room); }
    function deleteRoom(id) { const room=getRoom(id); if (!room || room.owner !== playerId()) return; const remove=()=>{ writeRooms(readRooms().filter(item=>item.id!==id)); if(activeRoomId===id){activeRoomId=null;game=null;sessionStorage.removeItem('ulivre_blackjack_active_room');} renderLobby(); }; if(window.openRoomDeleteDialog) window.openRoomDeleteDialog(remove); else remove(); }
    function startRoom(room) { game={ room, viewOnly:!room.players.some(player=>player.id===playerId()), hand:room.game?.hands?.[playerId()]||[], dealer:room.game?.dealer||[], status:room.game?.status||'waiting', bet:room.game?.bets?.[playerId()]||0, message:room.game?.message||'', history:room.game?.history||[] }; renderGame(); }
    function persist() { const room=getRoom(); if(!room||!game)return; room.game={...(room.game||{}),hands:{...(room.game?.hands||{}),[playerId()]:game.hand},dealer:game.dealer,status:game.status,bets:{...(room.game?.bets||{}),[playerId()]:game.bet},message:game.message,history:game.history}; writeRooms(readRooms().map(item=>item.id===room.id?room:item)); }
    function startHand() { const room=getRoom(); const balance=wallet(); const bet=Math.floor(Number(panel().querySelector('#blackjackBet')?.value)); if(!room||room.players.length<2||game.status==='playing'||!Number.isFinite(bet)||bet<1||bet>MAX_BET||bet>balance.coins)return; saveWallet({...balance,coins:balance.coins-bet,hands:balance.hands+1}); const hands={}; const bets={}; room.players.forEach(player=>{hands[player.id]=[drawCard(),drawCard()];bets[player.id]=bet;}); room.game={hands,dealer:[drawCard(),drawCard()],status:'playing',bets,stood:{},message:tx('blackjack_your_turn','Sua vez: compre uma carta ou pare.'),history:room.game?.history||[]}; writeRooms(readRooms().map(item=>item.id===room.id?room:item)); startRoom(room); }
    function botTurn(room) { const bot=room.players.find(player=>player.isBot); if(!bot)return; const botHand=[drawCard(),drawCard()]; while(score(botHand)<17)botHand.push(drawCard()); room.game.hands[bot.id]=botHand; finishHand(room); }
    function hit() { if(!game||game.status!=='playing'||game.viewOnly)return; game.hand.push(drawCard()); if(score(game.hand)>21) { const room=getRoom(); room.game.stood={...(room.game.stood||{}),[playerId()]:true}; const everyoneStood=room.players.every(player=>room.game.stood[player.id]); if(room.mode==='bot'||everyoneStood){while(score(room.game.dealer)<17)room.game.dealer.push(drawCard());finishHand(room);} else {room.game.message=tx('blackjack_waiting_player','Aguardando jogador');writeRooms(readRooms().map(item=>item.id===room.id?room:item));startRoom(room);} } else { game.message=tx('blackjack_hit_message','Você comprou uma carta.'); persist(); renderGame(); } }
    function stand() { if(!game||game.status!=='playing'||game.viewOnly)return; const room=getRoom(); room.game.stood={...(room.game.stood||{}),[playerId()]:true}; const everyoneStood=room.players.every(player=>room.game.stood[player.id]); if(room.mode==='bot'||everyoneStood){while(score(room.game.dealer)<17)room.game.dealer.push(drawCard()); finishHand(room);} else { room.game.message=tx('blackjack_waiting_player','Aguardando jogador'); writeRooms(readRooms().map(item=>item.id===room.id?room:item)); startRoom(room); } }
    function finishHand(room) { if(!room?.game)return; const me=room.game.hands[playerId()]||game?.hand||[]; const dealer=room.game.dealer||[]; const mine=score(me); const house=score(dealer); let result=''; let delta=0; const bet=room.game.bets?.[playerId()]||0; if(mine>21) { result=tx('blackjack_bust','Você estourou.'); delta=-bet; } else if(house>21||mine>house) { result=tx('blackjack_win','Você venceu!'); delta=bet; } else if(mine===house) { result=tx('blackjack_push','Empate: aposta devolvida.'); delta=0; } else { result=tx('blackjack_loss','A casa venceu.'); delta=-bet; } const balance=wallet(); saveWallet({...balance,coins:balance.coins+(delta>0?bet+delta:delta===0?bet:0),wins:balance.wins+(delta>0?1:0)}); room.game.status='finished'; room.game.message=`${result} ${tx('blackjack_score','Pontuação')}: ${mine} × ${house}`; room.game.history=[room.game.message,...(room.game.history||[])].slice(0,8); writeRooms(readRooms().map(item=>item.id===room.id?room:item)); startRoom(room); }
    const cardMarkup=(card,hidden=false)=>`<span class="blackjack-playing-card ${card.suit==='♥'||card.suit==='♦'?'red':''} ${hidden?'hidden-card':''}">${hidden?'◆':escapeHtml(card.rank+card.suit)}</span>`;
    function doubleDown() { if(!game||game.status!=='playing'||game.viewOnly||game.hand.length!==2)return; const balance=wallet(); if(balance.coins<game.bet)return; saveWallet({...balance,coins:balance.coins-game.bet,hands:balance.hands+1}); game.bet*=2; game.hand.push(drawCard()); const room=getRoom(); room.game.bets[playerId()]=game.bet; room.game.hands[playerId()]=game.hand; room.game.stood={...(room.game.stood||{}),[playerId()]:true}; if(score(game.hand)>21){room.game.message=tx('blackjack_bust','Você estourou.');} while(score(room.game.dealer)<17)room.game.dealer.push(drawCard()); finishHand(room); }
    function enhanceTable() { const target=panel(); if(!target||!target.querySelector('.blackjack-table'))return; const dealerSeat=target.querySelector('.blackjack-seat'); dealerSeat?.querySelector('h5 .blackjack-playing-card')?.remove(); const dealerCards=dealerSeat?.querySelectorAll('.blackjack-hand .blackjack-playing-card')||[]; dealerCards.forEach((card,index)=>{const room=getRoom(); const hidden=room?.game?.status==='playing'&&index===1; const nextText=hidden?'◆':card.dataset.cardLabel||card.textContent; card.classList.toggle('hidden-card',hidden); if(card.textContent!==nextText)card.textContent=nextText;}); const actions=target.querySelector('.blackjack-actions'); if(actions&&!target.querySelector('#blackjackDouble')&&game?.status==='playing'&&!game.viewOnly&&game.hand.length===2){const button=document.createElement('button');button.id='blackjackDouble';button.className='blackjack-secondary';button.type='button';button.textContent=tx('blackjack_double','Dobrar');button.addEventListener('click',doubleDown);actions.appendChild(button);} }
    if(panel())new MutationObserver(enhanceTable).observe(panel(),{childList:true,subtree:true});
    function renderLobby() { const target=panel(); const rooms=readRooms(); const balance=wallet(); target.innerHTML=`<div class="blackjack-card"><div class="blackjack-header"><div><h4>${tx('blackjack_title','Blackjack')}</h4><p>${tx('blackjack_subtitle','Jogue contra o bot ou com a comunidade.')}</p></div><div class="blackjack-balance"><span>${tx('blackjack_coins','moedas')}: <strong>${balance.coins}</strong></span></div></div><div class="blackjack-create"><label class="blackjack-field">${tx('blackjack_play_with','Jogar com')}<select id="blackjackMode" class="blackjack-select"><option value="bot">${tx('blackjack_bot','Bot')}</option><option value="community">${tx('blackjack_community','Comunidade')}</option></select></label><span></span><button id="blackjackCreate" class="blackjack-primary" type="button">${tx('blackjack_create','Criar sala')}</button></div><div class="blackjack-room-list"><h5>${tx('blackjack_rooms','Salas disponíveis')}</h5>${rooms.length?rooms.map(room=>`<div class="blackjack-room"><div class="blackjack-room-meta"><strong>${escapeHtml(room.id)}</strong><span class="blackjack-muted">${room.mode==='bot'?tx('blackjack_bot','Bot'):tx('blackjack_community','Comunidade')} · ${room.players.length}/${room.capacity}</span></div><div class="blackjack-room-actions">${room.mode==='community'&&room.players.length<room.capacity?`<button class="blackjack-secondary blackjack-join" data-room="${escapeHtml(room.id)}" type="button">${tx('blackjack_join','Entrar')}</button>`:''}<button class="blackjack-secondary blackjack-view" data-room="${escapeHtml(room.id)}" type="button">${tx('blackjack_view','Visualizar')}</button>${room.owner===playerId()?`<button class="blackjack-danger blackjack-delete" data-room="${escapeHtml(room.id)}" type="button">${tx('blackjack_delete','Apagar')}</button>`:''}</div></div>`).join(''):`<p class="blackjack-muted">${tx('blackjack_no_rooms','Nenhuma sala aberta ainda.')}</p>`}</div></div>`; target.querySelector('#blackjackCreate').addEventListener('click',createRoom); target.querySelectorAll('.blackjack-join').forEach(button=>button.addEventListener('click',()=>joinRoom(button.dataset.room))); target.querySelectorAll('.blackjack-view').forEach(button=>button.addEventListener('click',()=>{const room=getRoom(button.dataset.room);if(room)startRoom(room);})); target.querySelectorAll('.blackjack-delete').forEach(button=>button.addEventListener('click',()=>deleteRoom(button.dataset.room))); }
    function renderGame() { const target=panel(); const room=game.room; const dealer=room.game?.dealer||game.dealer; const opponent=room.players.find(player=>player.id!==playerId()); const hand=game.hand||room.game?.hands?.[playerId()]||[]; const canStart=!game.viewOnly&&room.players.length>=2&&game.status!=='playing'; target.innerHTML=`<div class="blackjack-card"><div class="blackjack-header"><div><h4>${tx('blackjack_room','Sala')} ${escapeHtml(room.id)}</h4><p>${room.mode==='bot'?tx('blackjack_bot','Bot'):tx('blackjack_community','Comunidade')} · ${room.players.length}/2</p></div><button id="blackjackBack" class="blackjack-secondary" type="button">${tx('blackjack_back','Voltar')}</button></div><div class="blackjack-balance"><span>${tx('blackjack_coins','moedas')}: <strong>${wallet().coins}</strong></span></div><div class="blackjack-table"><div class="blackjack-seat"><h5>${tx('blackjack_dealer','Dealer')} · ${room.game?.status==='finished'?score(dealer):'?'} ${dealer.map(card=>cardMarkup(card)).join('')}</h5><div class="blackjack-hand">${dealer.map(card=>cardMarkup(card)).join('')}</div></div><div class="blackjack-seat"><h5>${escapeHtml(userName())} · ${hand.length?score(hand):''}</h5><div class="blackjack-hand">${hand.length?hand.map(cardMarkup).join(''):`<span class="blackjack-muted">${tx('blackjack_waiting_hand','Aguardando mão.')}</span>`}</div></div><div class="blackjack-status">${escapeHtml(room.game?.message||tx('blackjack_ready','Crie ou entre em uma sala para começar.'))}</div>${canStart?`<div class="blackjack-bet"><label class="blackjack-field">${tx('blackjack_bet','Aposta')}<input id="blackjackBet" class="blackjack-input" type="number" min="1" max="250" value="10"></label><button id="blackjackStart" class="blackjack-primary" type="button">${tx('blackjack_deal','Distribuir')}</button></div>`:''}${room.game?.status==='playing'&&!game.viewOnly?`<div class="blackjack-actions"><button id="blackjackHit" class="blackjack-primary" type="button">${tx('blackjack_hit','Comprar carta')}</button><button id="blackjackStand" class="blackjack-secondary" type="button">${tx('blackjack_stand','Parar')}</button></div>`:''}<div class="blackjack-rules"><h5>${tx('blackjack_rules_title','Como jogar')}</h5>${tx('blackjack_rules','Chegue o mais perto possível de 21 sem passar. Figuras valem 10, Ás vale 1 ou 11. Vença o dealer para receber o dobro da aposta.')}</div></div><div class="blackjack-history">${(room.game?.history||[]).map(item=>`<span>${escapeHtml(item)}</span>`).join('')||tx('blackjack_no_history','Nenhuma rodada finalizada.')}</div></div>`; target.querySelector('#blackjackBack')?.addEventListener('click',renderLobby); target.querySelector('#blackjackStart')?.addEventListener('click',startHand); target.querySelector('#blackjackHit')?.addEventListener('click',hit); target.querySelector('#blackjackStand')?.addEventListener('click',stand); }
    function show() { document.getElementById('gamesMenuScreen')?.setAttribute('hidden',''); document.getElementById('gameShellScreen')?.removeAttribute('hidden'); ['chessPanel','impostorPanel','hangmanPanel','checkersPanel','roulettePanel','unoPanel','bichoPanel','slotsPanel','pokerPanel'].forEach(id=>{const element=document.getElementById(id);element?.setAttribute('hidden','');if(element)element.style.setProperty('display','none','important');}); document.querySelectorAll('.chess-room-creator,.chess-opponent-panel,#chessRoomList,#tttRoomList,.game-stage').forEach(element=>{element.hidden=true;element.style.display='none';}); const target=panel();if(!target)return;target.hidden=false;target.style.setProperty('display','block','important');document.querySelector('.game-shell-title-wrap strong').textContent=tx('blackjack_title','Blackjack');document.getElementById('chessStatusText').textContent=tx('blackjack_status','Jogue contra o bot ou com a comunidade.');activeRoomId=sessionStorage.getItem('ulivre_blackjack_active_room')||null;const room=getRoom();if(room)startRoom(room);else renderLobby(); }
    window.addEventListener('storage',event=>{if(event.key===ROOMS_KEY||event.key===WALLET_KEY){const room=getRoom();if(room&&game)startRoom(room);else if(!panel()?.hidden)renderLobby();}});
    window.addEventListener('languageChanged',()=>{if(!panel()?.hidden){const room=getRoom();if(room)startRoom(room);else renderLobby();}});
    window.BlackjackGame={show};
}());
