(function () {
    'use strict';

    const ROOMS_KEY = 'ulivre_poker_rooms';
    const WALLET_KEY = 'ulivre_poker_wallets';
    const STARTING_COINS = 250;
    const MAX_BET = 250;
    const SUITS = ['♠', '♥', '♦', '♣'];
    const RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
    let activeRoomId = null;
    let game = null;

    const panel = () => document.getElementById('pokerPanel');
    const tx = (key, fallback, replacements = {}) => { const value = typeof window.t === 'function' ? window.t(key, replacements) : key; return value === key ? fallback : value; };
    const userName = () => (localStorage.getItem('userProfileName') || tx('games_room_player_label', 'Jogador')).trim();
    const playerId = () => { let id = sessionStorage.getItem('ulivre_poker_player_id'); if (!id) { id = `poker-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; sessionStorage.setItem('ulivre_poker_player_id', id); } return id; };
    const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
    function readRooms() { try { const rooms = JSON.parse(localStorage.getItem(ROOMS_KEY) || '[]'); return Array.isArray(rooms) ? rooms.filter(room => window.UniversidadeLivreGameScope?.matchesRoom(room) ?? true) : []; } catch (_) { return []; } }
    function writeRooms(rooms) { let existing = []; try { existing = JSON.parse(localStorage.getItem(ROOMS_KEY) || '[]'); } catch (_) {} const otherScopes = Array.isArray(existing) ? existing.filter(room => !(window.UniversidadeLivreGameScope?.matchesRoom(room) ?? true)) : []; localStorage.setItem(ROOMS_KEY, JSON.stringify([...otherScopes, ...rooms].slice(-20))); }
    const getRoom = (id = activeRoomId) => readRooms().find(room => room.id === id) || null;
    function wallet() { if (window.UniversidadeLivreWallet) return window.UniversidadeLivreWallet.get(); let wallets = {}; try { wallets = JSON.parse(localStorage.getItem(WALLET_KEY) || '{}'); } catch (_) {} if (!wallets[userName()]) wallets[userName()] = { coins: STARTING_COINS, karma: 0, hands: 0, wins: 0 }; return wallets[userName()]; }
    function saveWallet(value) { if (window.UniversidadeLivreWallet) { window.UniversidadeLivreWallet.update(value); return; } let wallets = {}; try { wallets = JSON.parse(localStorage.getItem(WALLET_KEY) || '{}'); } catch (_) {} wallets[userName()] = { ...value, coins: Math.max(0, Math.floor(value.coins)), karma: Math.max(0, Math.floor(value.karma)) }; localStorage.setItem(WALLET_KEY, JSON.stringify(wallets)); }
    function deck() { return SUITS.flatMap(suit => RANKS.map((rank, index) => ({ rank, suit, value: index + 2 }))); }
    function shuffle(cards) { return [...cards].sort(() => Math.random() - .5); }
    function dealHand() { return shuffle(deck()).slice(0, 5); }
    function handScore(hand) { const counts = {}; hand.forEach(card => { counts[card.value] = (counts[card.value] || 0) + 1; }); const groups = Object.entries(counts).map(([value, count]) => [count, Number(value)]).sort((a, b) => b[0] - a[0] || b[1] - a[1]); const values = hand.map(card => card.value).sort((a, b) => b - a); const flush = hand.every(card => card.suit === hand[0].suit); const unique = [...new Set(values)]; const straight = unique.length === 5 && (unique[0] - unique[4] === 4 || JSON.stringify(unique) === JSON.stringify([14, 5, 4, 3, 2])); if (straight && flush) return [8, values[0]]; if (groups[0][0] === 4) return [7, ...groups[0], groups[1][1]]; if (groups[0][0] === 3 && groups[1]?.[0] === 2) return [6, groups[0][1], groups[1][1]]; if (flush) return [5, ...values]; if (straight) return [4, values[0]]; if (groups[0][0] === 3) return [3, groups[0][1], ...groups.slice(1).map(item => item[1])]; if (groups[0][0] === 2 && groups[1]?.[0] === 2) return [2, groups[0][1], groups[1][1], groups[2][1]]; if (groups[0][0] === 2) return [1, groups[0][1], ...groups.slice(1).map(item => item[1])]; return [0, ...values]; }
    function compareHands(a, b) { const left = handScore(a); const right = handScore(b); for (let i = 0; i < Math.max(left.length, right.length); i += 1) { if ((left[i] || 0) !== (right[i] || 0)) return (left[i] || 0) > (right[i] || 0) ? 1 : -1; } return 0; }
    function handLabel(hand) { const score = handScore(hand)[0]; return ['Carta alta', 'Par', 'Dois pares', 'Trinca', 'Sequência', 'Flush', 'Full house', 'Quadra', 'Straight flush'][score]; }
    function createRoom() { const target = panel(); const mode = target.querySelector('#pokerMode')?.value || 'community'; const difficulty = target.querySelector('#pokerDifficulty')?.value || 'intermediario'; const room = window.UniversidadeLivreGameScope?.decorateRoom({ id: `POK-${Math.random().toString(36).slice(2, 7).toUpperCase()}`, owner: playerId(), mode, difficulty, players: [{ id: playerId(), name: userName() }], capacity: 2, createdAt: Date.now(), game: null }); if (mode === 'bot') room.players.push({ id: `bot-${room.id}`, name: 'Bot', isBot: true }); activeRoomId = room.id; sessionStorage.setItem('ulivre_poker_active_room', activeRoomId); writeRooms([...readRooms(), room]); startRoom(room); }
    function joinRoom(id) { const room = getRoom(id); if (!room || room.mode === 'bot' || room.players.length >= room.capacity) return; room.players.push({ id: playerId(), name: userName() }); activeRoomId = id; sessionStorage.setItem('ulivre_poker_active_room', id); writeRooms(readRooms().map(item => item.id === id ? room : item)); startRoom(room); }
    function deleteRoom(id) { const room = getRoom(id); if (!room || room.owner !== playerId()) return; const remove = () => { writeRooms(readRooms().filter(item => item.id !== id)); if (activeRoomId === id) { activeRoomId = null; game = null; sessionStorage.removeItem('ulivre_poker_active_room'); } renderLobby(); }; if (window.openRoomDeleteDialog) window.openRoomDeleteDialog(remove); else remove(); }
    function startRoom(room) { game = { room, viewOnly: !room.players.some(player => player.id === playerId()), hand: room.game?.hands?.[playerId()] || null, revealed: room.game?.revealed?.[playerId()] || false, status: room.game?.status || 'waiting', message: room.game?.message || '', pot: room.game?.pot || 0, history: room.game?.history || [] }; renderGame(); }
    function persistGame() { const room = getRoom(); if (!room || !game) return; room.game = { ...(room.game || {}), hands: { ...(room.game?.hands || {}), [playerId()]: game.hand }, revealed: { ...(room.game?.revealed || {}), [playerId()]: game.revealed }, status: game.status, message: game.message, pot: game.pot, history: game.history }; writeRooms(readRooms().map(item => item.id === room.id ? room : item)); }
    function startHand() { const room = getRoom(); if (!room || room.players.length < 2 || game?.status === 'playing') return; const hands = {}; room.players.forEach(player => { hands[player.id] = dealHand(); }); room.game = { hands, revealed: {}, status: 'playing', message: tx('poker_hand_started', 'Mãos distribuídas. Revele sua mão quando estiver pronto.'), pot: 0, history: room.game?.history || [] }; writeRooms(readRooms().map(item => item.id === room.id ? room : item)); startRoom(room); if (room.mode === 'bot') setTimeout(revealBotHand, 700); }
    function revealBotHand() { const room = getRoom(); if (!room?.game || room.game.status !== 'playing') return; const bot = room.players.find(player => player.isBot); if (!bot) return; room.game.revealed = { ...(room.game.revealed || {}), [bot.id]: true }; room.game.message = tx('poker_waiting_opponent', 'Aguardando o outro jogador revelar a mão.'); writeRooms(readRooms().map(item => item.id === room.id ? room : item)); if (room.game.revealed[playerId()]) finishHand(); else startRoom(room); }
    function revealHand(isBot = false) { const room = getRoom(); if (!room || !game?.hand || game.revealed) return; const bet = isBot ? 0 : Math.floor(Number(panel().querySelector('#pokerBet')?.value)); if (!isBot) { const balance = wallet(); if (!Number.isFinite(bet) || bet < 1 || bet > MAX_BET || bet > balance.coins) { game.message = tx('poker_invalid_bet', 'Escolha uma aposta entre 1 e 250 moedas, dentro do seu saldo.'); renderGame(); return; } saveWallet({ ...balance, coins: balance.coins - bet, hands: balance.hands + 1 }); game.pot += bet; } game.revealed = true; persistGame(); const current = getRoom(); const playerIds = current.players.map(player => player.id); const revealed = current.game?.revealed || {}; const allRevealed = playerIds.every(id => revealed[id]); if (allRevealed) finishHand(); else { game.message = tx('poker_waiting_opponent', 'Aguardando o outro jogador revelar a mão.'); persistGame(); renderGame(); } }
    function finishHand() { const room = getRoom(); const hands = room.game.hands; const ids = room.players.map(player => player.id); const winner = compareHands(hands[ids[0]], hands[ids[1]]); const payout = room.game.pot; const result = winner === 0 ? tx('poker_draw', 'Empate: o pote foi dividido.') : winner > 0 ? `${escapeHtml(room.players[0].name)} ${tx('poker_wins', 'venceu a mão.')}` : `${escapeHtml(room.players[1].name)} ${tx('poker_wins', 'venceu a mão.')}`; room.game.status = 'finished'; room.game.message = result; room.game.history = [{ result, at: Date.now() }, ...(room.game.history || [])].slice(0, 8); writeRooms(readRooms().map(item => item.id === room.id ? room : item)); if (winner === 0) { const balance = wallet(); saveWallet({ ...balance, coins: balance.coins + Math.floor(payout / 2), karma: balance.karma + 1 }); } else if ((winner > 0 && ids[0] === playerId()) || (winner < 0 && ids[1] === playerId())) { const balance = wallet(); saveWallet({ ...balance, coins: balance.coins + payout, karma: balance.karma + 3, wins: balance.wins + 1 }); } startRoom(room); }
    function cardMarkup(card, hidden) { return `<span class="poker-playing-card ${card.suit === '♥' || card.suit === '♦' ? 'red' : ''} ${hidden ? 'hidden-card' : ''}" data-rank="${escapeHtml(card.rank)}" data-suit="${escapeHtml(card.suit)}">${hidden ? '◆' : `${card.rank}${card.suit}`}</span>`; }
    function addPokerRules() {
        const target = panel();
        if (!target || !target.querySelector('.poker-card') || target.querySelector('.poker-rules')) return;
        const rules = document.createElement('section');
        rules.className = 'poker-rules';
        rules.innerHTML = `<div><h5>${tx('poker_how_to_play', 'Como jogar')}</h5><p>${tx('poker_how_to_play_text', 'Receba cinco cartas, escolha uma aposta e revele sua mão. A maior combinação vence e leva o pote.')}</p></div><div><h5>${tx('poker_hand_ranking', 'Ranking das mãos')}</h5><ol><li><strong>${tx('poker_rank_straight_flush', 'Straight flush')}</strong><span>${tx('poker_rank_straight_flush_desc', 'Sequência do mesmo naipe')}</span></li><li><strong>${tx('poker_rank_four', 'Quadra')}</strong><span>${tx('poker_rank_four_desc', 'Quatro cartas do mesmo valor')}</span></li><li><strong>${tx('poker_rank_full_house', 'Full house')}</strong><span>${tx('poker_rank_full_house_desc', 'Uma trinca e um par')}</span></li><li><strong>${tx('poker_rank_flush', 'Flush')}</strong><span>${tx('poker_rank_flush_desc', 'Cinco cartas do mesmo naipe')}</span></li><li><strong>${tx('poker_rank_straight', 'Sequência')}</strong><span>${tx('poker_rank_straight_desc', 'Cinco valores consecutivos')}</span></li><li><strong>${tx('poker_rank_three', 'Trinca')}</strong><span>${tx('poker_rank_three_desc', 'Três cartas do mesmo valor')}</span></li><li><strong>${tx('poker_rank_pair', 'Par')}</strong><span>${tx('poker_rank_pair_desc', 'Duas cartas do mesmo valor')}</span></li></ol></div>`;
        target.querySelector('.poker-card').appendChild(rules);
    }
    if (panel()) new MutationObserver(addPokerRules).observe(panel(), { childList: true, subtree: true });
    function renderLobby() { const target = panel(); const rooms = readRooms(); const balance = wallet(); target.innerHTML = `<div class="poker-card"><div class="poker-header"><div><h4>${tx('poker_title', 'Poker')}</h4><p>${tx('poker_subtitle', 'Jogue uma mão de poker contra o bot ou com a comunidade.')}</p></div><div class="poker-balance"><span>${tx('poker_coins', 'moedas')}: <strong>${balance.coins}</strong></span><span>${tx('poker_karma', 'carma')}: <strong>${balance.karma}</strong></span></div></div><div class="poker-create"><label class="poker-field">${tx('poker_play_with', 'Jogar com')}<select id="pokerMode" class="poker-select"><option value="bot">${tx('poker_bot', 'Bot')}</option><option value="community">${tx('poker_community', 'Comunidade')}</option></select></label><label class="poker-field">${tx('poker_difficulty', 'Nível do bot')}<select id="pokerDifficulty" class="poker-select"><option value="iniciante">${tx('games_room_level_beginner', 'Iniciante')}</option><option value="intermediario" selected>${tx('games_room_level_intermediate', 'Intermediário')}</option><option value="avancado">${tx('games_room_level_advanced', 'Avançado')}</option><option value="mestre">${tx('games_room_level_master', 'Mestre')}</option></select></label><button class="poker-primary" id="pokerCreate" type="button"><i class="fas fa-plus"></i> ${tx('poker_create_room', 'Criar sala')}</button></div><div class="poker-room-list"><h5>${tx('poker_open_rooms', 'Salas disponíveis')}</h5>${rooms.length ? rooms.map(room => `<div class="poker-room"><div class="poker-room-meta"><strong>${escapeHtml(room.id)}</strong><span class="poker-muted">${room.mode === 'bot' ? tx('poker_bot', 'Bot') : tx('poker_community', 'Comunidade')} · ${room.players.length}/${room.capacity}</span></div><div class="poker-room-actions">${room.mode === 'community' && room.players.length < room.capacity ? `<button class="poker-secondary poker-join" data-room="${escapeHtml(room.id)}" type="button">${tx('poker_join', 'Entrar')}</button>` : ''}<button class="poker-secondary poker-view" data-room="${escapeHtml(room.id)}" type="button">${tx('poker_view', 'Visualizar')}</button>${room.owner === playerId() ? `<button class="poker-danger poker-delete" data-room="${escapeHtml(room.id)}" type="button"><i class="fas fa-trash"></i> ${tx('poker_delete', 'Apagar')}</button>` : ''}</div></div>`).join('') : `<p class="poker-muted">${tx('poker_no_rooms', 'Nenhuma sala aberta ainda.')}</p>`}</div></div>`; target.querySelector('#pokerCreate').addEventListener('click', createRoom); target.querySelectorAll('.poker-join').forEach(button => button.addEventListener('click', () => joinRoom(button.dataset.room))); target.querySelectorAll('.poker-view').forEach(button => button.addEventListener('click', () => { const room = getRoom(button.dataset.room); if (room) startRoom(room); })); target.querySelectorAll('.poker-delete').forEach(button => button.addEventListener('click', () => deleteRoom(button.dataset.room))); }
    function renderGame() { const target = panel(); const room = game.room; const balance = wallet(); const visibleHand = game.hand || room.game?.hands?.[playerId()] || []; const opponent = room.players.find(player => player.id !== playerId()); const opponentHand = room.game?.hands?.[opponent?.id] || []; const canStart = !game.viewOnly && room.players.length >= 2 && (!room.game || room.game.status !== 'playing'); const history = (room.game?.history || []).map(item => `<span>${escapeHtml(item.result)}</span>`).join('') || `<span>${tx('poker_no_history', 'Nenhuma mão finalizada.')}</span>`; target.innerHTML = `<div class="poker-card"><div class="poker-header"><div><h4>${tx('poker_room', 'Sala')} ${escapeHtml(room.id)}</h4><p>${room.mode === 'bot' ? `${tx('poker_bot', 'Bot')} · ${escapeHtml(room.difficulty)}` : `${tx('poker_community', 'Comunidade')} · ${room.players.length}/2`}</p></div><button class="poker-secondary" id="pokerBack" type="button">${tx('poker_back', 'Voltar')}</button></div><div class="poker-balance"><span>${tx('poker_coins', 'moedas')}: <strong>${balance.coins}</strong></span><span>${tx('poker_karma', 'carma')}: <strong>${balance.karma}</strong></span><span>${tx('poker_pot', 'pote')}: <strong>${room.game?.pot || 0}</strong></span></div><div class="poker-table"><div class="poker-seat"><h5>${escapeHtml(userName())}</h5><div class="poker-hand">${visibleHand.length ? visibleHand.map(card => cardMarkup(card, !game.revealed)).join('') : `<span class="poker-muted">${tx('poker_waiting_hand', 'Aguardando distribuição.')}</span>`}</div></div><div class="poker-seat"><h5>${escapeHtml(opponent?.name || tx('poker_waiting_player', 'Aguardando jogador'))}</h5><div class="poker-hand">${opponentHand.length ? opponentHand.map(card => cardMarkup(card, room.game?.status !== 'finished' || !room.game?.revealed?.[opponent.id])).join('') : `<span class="poker-muted">${tx('poker_waiting_player', 'Aguardando jogador')}</span>`}</div></div><div class="poker-status">${escapeHtml(room.game?.message || tx('poker_ready', 'Crie ou entre em uma sala para começar.'))}</div>${canStart ? `<button class="poker-primary" id="pokerStart" type="button">${tx('poker_start_hand', 'Distribuir mão')}</button>` : ''}${room.game?.status === 'playing' && game.hand && !game.revealed && !game.viewOnly ? `<div class="poker-bet"><label class="poker-field">${tx('poker_bet', 'Aposta')}<input id="pokerBet" class="poker-input" type="number" min="1" max="250" value="10"></label><button class="poker-primary" id="pokerReveal" type="button">${tx('poker_reveal', 'Apostar e revelar')}</button></div>` : ''}</div><div class="poker-history">${history}</div></div>`; target.querySelector('#pokerBack')?.addEventListener('click', renderLobby); target.querySelector('#pokerStart')?.addEventListener('click', startHand); target.querySelector('#pokerReveal')?.addEventListener('click', () => revealHand()); }
    function show() { document.getElementById('gamesMenuScreen')?.setAttribute('hidden', ''); document.getElementById('gameShellScreen')?.removeAttribute('hidden'); ['chessPanel', 'impostorPanel', 'hangmanPanel', 'checkersPanel', 'roulettePanel', 'unoPanel', 'bichoPanel', 'slotsPanel'].forEach(id => { const element = document.getElementById(id); element?.setAttribute('hidden', ''); if (element) element.style.setProperty('display', 'none', 'important'); }); document.querySelectorAll('.chess-room-creator, .chess-opponent-panel, #chessRoomList, #tttRoomList, .game-stage').forEach(element => { element.hidden = true; element.style.display = 'none'; }); const target = panel(); if (!target) return; target.hidden = false; target.style.setProperty('display', 'block', 'important'); document.querySelector('.game-shell-title-wrap strong').textContent = tx('poker_title', 'Poker'); document.getElementById('chessStatusText').textContent = tx('poker_status', 'Jogue contra o bot ou com a comunidade.'); activeRoomId = sessionStorage.getItem('ulivre_poker_active_room') || null; const room = getRoom(); if (room) startRoom(room); else renderLobby(); }
    window.addEventListener('storage', event => { if (event.key === ROOMS_KEY || event.key === WALLET_KEY) { const room = getRoom(); if (room && game) startRoom(room); else if (!panel()?.hidden) renderLobby(); } });
    window.addEventListener('languageChanged', () => { if (!panel()?.hidden) { const room = getRoom(); if (room) startRoom(room); else renderLobby(); } });
    window.PokerGame = { show };
}());
