(function () {
    'use strict';

    const SIZE = 8;
    const ROOMS_KEY = 'ulivre_checkers_rooms';
    const STATE_KEY = 'ulivre_checkers_states';
    const SCORE_KEY = 'ulivre_checkers_scores';
    let game = null;
    let botTimer = null;

    function tx(key, fallback, replacements = {}) { const value = typeof window.t === 'function' ? window.t(key, replacements) : key; return value === key ? fallback : value; }
    function getPanel() { return document.getElementById('checkersPanel'); }
    function escapeHtml(value) { return String(value || '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
    function getUserName() { return (window.currentUserName || localStorage.getItem('userProfileName') || tx('games_room_player_label', 'Jogador')).trim() || tx('games_room_player_label', 'Jogador'); }
    function levelLabel(level) { return ({ iniciante: tx('games_room_level_beginner', 'Iniciante'), intermediario: tx('games_room_level_intermediate', 'Intermediário'), avancado: tx('games_room_level_advanced', 'Avançado'), mestre: tx('games_room_level_master', 'Mestre') }[level] || tx('games_room_level_intermediate', 'Intermediário')); }
    function readRooms() { try { const rooms = JSON.parse(localStorage.getItem(ROOMS_KEY) || '[]'); return Array.isArray(rooms) ? rooms : []; } catch (_) { return []; } }
    function writeRooms(rooms) { localStorage.setItem(ROOMS_KEY, JSON.stringify(rooms.slice(-20))); }
    function readStates() { try { const states = JSON.parse(localStorage.getItem(STATE_KEY) || '{}'); return states && typeof states === 'object' ? states : {}; } catch (_) { return {}; } }
    function writeState(id, state) { const states = readStates(); states[id] = state; localStorage.setItem(STATE_KEY, JSON.stringify(states)); }
    function readState(id) { return readStates()[id] || null; }
    function roomId() { return `DAM-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 5).toUpperCase()}`; }
    function clearGame() { clearTimeout(botTimer); game = null; }
    function newBoard() { const board = Array.from({ length: SIZE }, () => Array(SIZE).fill(null)); for (let row = 0; row < 3; row += 1) for (let col = 0; col < SIZE; col += 1) if ((row + col) % 2) board[row][col] = { color: 'black', king: false }; for (let row = 5; row < SIZE; row += 1) for (let col = 0; col < SIZE; col += 1) if ((row + col) % 2) board[row][col] = { color: 'white', king: false }; return board; }
    function inside(row, col) { return row >= 0 && row < SIZE && col >= 0 && col < SIZE; }
    function opponent(color) { return color === 'white' ? 'black' : 'white'; }
    function directions(piece, capture = false) { if (piece.king || capture) return [[-1, -1], [-1, 1], [1, -1], [1, 1]]; const step = piece.color === 'white' ? -1 : 1; return [[step, -1], [step, 1]]; }
    function getMovesForPiece(board, row, col, capturesOnly = false) { const piece = board[row][col]; if (!piece) return []; const moves = []; directions(piece, capturesOnly).forEach(([dr, dc]) => { const nextRow = row + dr; const nextCol = col + dc; const jumpRow = row + dr * 2; const jumpCol = col + dc * 2; if (!capturesOnly && inside(nextRow, nextCol) && !board[nextRow][nextCol]) moves.push({ from: [row, col], to: [nextRow, nextCol], capture: null }); if (inside(jumpRow, jumpCol) && board[nextRow]?.[nextCol]?.color === opponent(piece.color) && !board[jumpRow][jumpCol]) moves.push({ from: [row, col], to: [jumpRow, jumpCol], capture: [nextRow, nextCol] }); }); return moves; }
    function getMoves(color, board = game.board) { const captures = []; const normal = []; board.forEach((line, row) => line.forEach((piece, col) => { if (piece?.color === color) { getMovesForPiece(board, row, col, true).forEach(move => captures.push(move)); getMovesForPiece(board, row, col, false).filter(move => !move.capture).forEach(move => normal.push(move)); } })); return captures.length ? captures : normal; }
    function availableMoves(color = game.turn) { return game.forcedFrom && color === game.turn ? getMovesForPiece(game.board, game.forcedFrom[0], game.forcedFrom[1], true) : getMoves(color); }
    function sameSquare(a, b) { return a && b && a[0] === b[0] && a[1] === b[1]; }
    function moveKey(move) { return `${move.to[0]}-${move.to[1]}`; }
    function applyMove(move) { const piece = game.board[move.from[0]][move.from[1]]; game.board[move.from[0]][move.from[1]] = null; game.board[move.to[0]][move.to[1]] = piece; if (move.capture) game.board[move.capture[0]][move.capture[1]] = null; if ((piece.color === 'white' && move.to[0] === 0) || (piece.color === 'black' && move.to[0] === SIZE - 1)) piece.king = true; return piece; }
    function finish(winner) { game.ended = true; game.winner = winner; if (!game.scored && !game.spectator) { const scores = JSON.parse(localStorage.getItem(SCORE_KEY) || '{}'); const score = scores[getUserName()] || { points: 0, wins: 0, losses: 0 }; if (winner === 'white') { score.points += 3; score.wins += 1; } else { score.losses += 1; } scores[getUserName()] = score; localStorage.setItem(SCORE_KEY, JSON.stringify(scores)); game.scored = true; window.dispatchEvent(new CustomEvent('checkersScoreUpdated', { detail: score })); } writeState(game.room.id, snapshot()); renderGame(); }
    function snapshot() { const { room, board, turn, selected, forcedFrom, ended, winner, lastAction, scores, spectator } = game; return { room, board, turn, selected, forcedFrom, ended, winner, lastAction, scores, spectator: false }; }
    function maybeFinish() { const whitePieces = game.board.flat().some(piece => piece?.color === 'white'); const blackPieces = game.board.flat().some(piece => piece?.color === 'black'); if (!whitePieces) { finish('black'); return true; } if (!blackPieces || getMoves(game.turn).length === 0) { finish(opponent(game.turn)); return true; } return false; }
    function selectPiece(row, col) { const piece = game.board[row][col]; if (!piece || piece.color !== game.turn || game.spectator || (game.turn === 'black' && game.room.mode === 'bot') || (game.forcedFrom && !sameSquare(game.forcedFrom, [row, col]))) return; const moves = availableMoves().filter(move => sameSquare(move.from, [row, col])); if (!moves.length) return; game.selected = [row, col]; renderGame(); }
    function playMove(move) { if (game.ended || game.spectator) return; const piece = applyMove(move); game.lastAction = `${piece.color === 'white' ? getUserName() : tx('games_room_bot', 'Bot')} ${tx('game_checkers_moved', 'moveu uma peça.')}`; if (move.capture) game.lastAction = `${piece.color === 'white' ? getUserName() : tx('games_room_bot', 'Bot')} ${tx('game_checkers_captured', 'fez uma captura.')}`; if (move.capture && getMovesForPiece(game.board, move.to[0], move.to[1], true).length) { game.selected = move.to; game.forcedFrom = move.to; writeState(game.room.id, snapshot()); renderGame(); if (game.turn === 'black') scheduleBot(); return; } game.selected = null; game.forcedFrom = null; game.turn = opponent(game.turn); if (!maybeFinish()) { writeState(game.room.id, snapshot()); renderGame(); if (game.turn === 'black' && game.room.mode === 'bot') scheduleBot(); } }
    function clickSquare(row, col) { if (!game || game.ended || game.spectator || (game.turn === 'black' && game.room.mode === 'bot')) return; if (game.selected) { const move = availableMoves().filter(item => sameSquare(item.from, game.selected)).find(item => sameSquare(item.to, [row, col])); if (move) { playMove(move); return; } } selectPiece(row, col); }
    function chooseBotMove() { const moves = availableMoves('black'); if (!moves.length) return null; if (game.room.difficulty === 'iniciante') return moves[Math.floor(Math.random() * moves.length)]; if (game.room.difficulty === 'intermediario') return moves.find(move => move.capture) || moves[Math.floor(Math.random() * moves.length)]; if (game.room.difficulty === 'avancado') return moves.sort((a, b) => Number(Boolean(b.capture)) - Number(Boolean(a.capture)))[0]; return moves.sort((a, b) => (b.capture ? 2 : 0) - (a.capture ? 2 : 0))[0]; }
    function scheduleBot() { clearTimeout(botTimer); if (!game || game.ended || game.spectator || game.turn !== 'black' || game.room.mode !== 'bot') return; game.lastAction = tx('game_checkers_bot_thinking', 'O bot está calculando a jogada...'); renderGame(); botTimer = setTimeout(() => { const move = chooseBotMove(); if (move) playMove(move); }, 750); }
    function createRoom() { const room = { id: roomId(), mode: document.getElementById('checkersMode').value, difficulty: document.getElementById('checkersDifficulty').value, players: 1, capacity: 2, createdBy: getUserName() }; const rooms = readRooms(); rooms.push(room); writeRooms(rooms); startRoom(room); }
    function joinRoom(id) { const room = readRooms().find(item => item.id === id); if (!room || room.players >= room.capacity) return; room.players += 1; writeRooms(readRooms().map(item => item.id === id ? room : item)); startRoom(room); }
    function viewRoom(id) { const room = readRooms().find(item => item.id === id); const state = readState(id); if (!room) return; if (!state) { const panel = getPanel(); panel.innerHTML = `<div class="checkers-card"><div class="checkers-header"><div><h4>${tx('games_room_room_label', 'Sala')} ${escapeHtml(room.id)}</h4><p>${tx('game_checkers_not_started', 'A partida ainda não começou.')}</p></div></div><button id="checkersBackPreview" class="checkers-secondary" type="button">${tx('game_room_back', 'Voltar às salas')}</button></div>`; panel.querySelector('#checkersBackPreview').addEventListener('click', renderLobby); return; } game = { ...state, room, spectator: true }; renderGame(); }
    function startRoom(room) { game = { room, board: newBoard(), turn: 'white', selected: null, forcedFrom: null, ended: false, winner: null, scores: { white: 0, black: 0 }, lastAction: tx('game_checkers_started', 'Partida iniciada.'), spectator: false }; writeState(room.id, snapshot()); renderGame(); }
    function renderLobby() { const panel = getPanel(); const rooms = readRooms(); panel.innerHTML = `<div class="checkers-card"><div class="checkers-header"><div><h4>${tx('game_checkers_title', 'Jogo de Damas')}</h4><p>${tx('game_checkers_description', 'Uma partida estratégica com capturas obrigatórias, promoção e bot inteligente.')}</p></div></div><div class="checkers-create"><label class="checkers-field">${tx('game_room_play_with', 'Jogar com')}<select id="checkersMode" class="checkers-select"><option value="bot">${tx('game_room_bots', 'Bot')}</option><option value="community">${tx('game_hangman_community', 'Comunidade')}</option></select></label><label class="checkers-field">${tx('game_hangman_level', 'Nível do bot')}<select id="checkersDifficulty" class="checkers-select"><option value="iniciante">${levelLabel('iniciante')}</option><option value="intermediario" selected>${levelLabel('intermediario')}</option><option value="avancado">${levelLabel('avancado')}</option><option value="mestre">${levelLabel('mestre')}</option></select></label><button id="checkersCreate" class="checkers-primary" type="button"><i class="fas fa-plus"></i> ${tx('game_hangman_create', 'Criar sala')}</button></div><div class="checkers-room-list"><h5>${tx('game_room_available', 'Salas disponíveis')}</h5>${rooms.length ? rooms.map(room => `<div class="checkers-room"><div class="checkers-room-meta"><strong>${escapeHtml(room.id)}</strong><span class="checkers-muted">${room.mode === 'bot' ? `Bot · ${levelLabel(room.difficulty)}` : tx('game_hangman_community', 'Comunidade')} · ${room.players}/2</span></div><div class="checkers-room-actions"><button class="checkers-primary checkers-join" data-room="${escapeHtml(room.id)}" type="button">${tx('game_hangman_join', 'Entrar')}</button><button class="checkers-secondary checkers-view" data-room="${escapeHtml(room.id)}" type="button">${tx('games_room_visualize', 'Visualizar')}</button><button class="checkers-danger checkers-delete" data-room="${escapeHtml(room.id)}" type="button">${tx('game_room_delete', 'Apagar sala')}</button></div></div>`).join('') : `<p class="checkers-muted">${tx('game_room_none', 'Nenhuma sala criada ainda.')}</p>`}</div></div>`; panel.querySelector('#checkersCreate').addEventListener('click', createRoom); panel.querySelectorAll('.checkers-join').forEach(button => button.addEventListener('click', () => joinRoom(button.dataset.room))); panel.querySelectorAll('.checkers-view').forEach(button => button.addEventListener('click', () => viewRoom(button.dataset.room))); panel.querySelectorAll('.checkers-delete').forEach(button => button.addEventListener('click', () => { writeRooms(readRooms().filter(room => room.id !== button.dataset.room)); renderLobby(); })); }
    function renderGame() { const panel = getPanel(); const moves = game.selected ? getMoves(game.turn).filter(move => sameSquare(move.from, game.selected)) : []; if (!game.spectator) writeState(game.room.id, snapshot()); const result = game.ended ? `<div class="checkers-result">${game.winner === 'white' ? tx('game_checkers_you_win', 'Você venceu!') : tx('game_checkers_bot_win', 'O bot venceu.')} <button id="checkersAgain" class="checkers-primary" type="button">${tx('game_hangman_new_word', 'Nova partida')}</button></div>` : ''; const squares = game.board.map((line, row) => line.map((piece, col) => { const isTarget = moves.some(move => sameSquare(move.to, [row, col])); const isCapture = moves.some(move => sameSquare(move.to, [row, col]) && move.capture); return `<button class="checkers-square ${(row + col) % 2 ? 'dark' : 'light'}${sameSquare(game.selected, [row, col]) ? ' selected' : ''}${isTarget ? ` move-target${isCapture ? ' capture-target' : ''}` : ''}" data-row="${row}" data-col="${col}" type="button">${piece ? `<span class="checkers-piece ${piece.color}${piece.king ? ' king' : ''}"></span>` : ''}</button>`; }).join('')).join(''); const winnerText = game.winner === 'white' ? getUserName() : tx('games_room_bot', 'Bot'); panel.innerHTML = `<div class="checkers-card"><div class="checkers-game-top"><div><h4>${tx('games_room_room_label', 'Sala')} ${escapeHtml(game.room.id)}</h4><span class="checkers-status">${game.spectator ? tx('game_checkers_viewing', 'Você está visualizando esta partida.') : game.ended ? `${tx('game_checkers_winner', 'Vencedor')}: ${escapeHtml(winnerText)}` : `${escapeHtml(game.lastAction)} · ${game.turn === 'white' ? getUserName() : tx('games_room_bot', 'Bot')}`}</span></div><button id="checkersBack" class="checkers-secondary" type="button">${tx('game_room_back', 'Voltar às salas')}</button></div><div class="checkers-score"><span>${tx('game_checkers_white', 'Brancas')}: ${game.board.flat().filter(piece => piece?.color === 'white').length}</span><span>${tx('game_checkers_black', 'Pretas')}: ${game.board.flat().filter(piece => piece?.color === 'black').length}</span><span>${game.spectator ? tx('game_checkers_viewing', 'Espectador') : game.turn === 'white' ? tx('game_checkers_your_turn', 'Sua vez') : tx('game_checkers_bot_turn', 'Vez do bot')}</span></div><div class="checkers-board${game.spectator ? ' viewer' : ''}">${squares}</div><p class="checkers-rules">${tx('game_checkers_rules', 'Capturas são obrigatórias. Alcance o outro lado para promover uma peça a dama.')}</p>${result}</div>`; panel.querySelector('#checkersBack').addEventListener('click', () => { clearGame(); renderLobby(); }); panel.querySelectorAll('.checkers-square').forEach(square => square.addEventListener('click', () => clickSquare(Number(square.dataset.row), Number(square.dataset.col)))); panel.querySelector('#checkersAgain')?.addEventListener('click', () => startRoom(game.room)); }
    function show() { const panel = getPanel(); if (!panel) return; document.getElementById('gamesMenuScreen')?.setAttribute('hidden', ''); document.getElementById('gameShellScreen')?.removeAttribute('hidden'); document.getElementById('chessPanel')?.setAttribute('hidden', ''); document.getElementById('impostorPanel')?.setAttribute('hidden', ''); document.getElementById('hangmanPanel')?.setAttribute('hidden', ''); document.querySelectorAll('.chess-room-creator, .chess-opponent-panel, #chessRoomList, #tttRoomList, .game-stage').forEach(element => { element.hidden = true; element.style.display = 'none'; }); panel.hidden = false; const title = document.querySelector('.game-shell-title-wrap strong'); const status = document.getElementById('chessStatusText'); if (title) title.textContent = tx('game_checkers_title', 'Jogo de Damas'); if (status) status.textContent = `${tx('game_checkers_title', 'Jogo de Damas')} · ${tx('game_room_available', 'Salas disponíveis')}`; renderLobby(); }
    window.addEventListener('languageChanged', () => { if (game) renderGame(); else if (!getPanel()?.hidden) renderLobby(); });
    window.addEventListener('storage', event => { if (game?.spectator && event.key === STATE_KEY) { const state = readState(game.room.id); if (state) { game = { ...state, room: game.room, spectator: true }; renderGame(); } } });
    window.CheckersGame = { show };
}());
